### ISSUE TITLE
About the query generator

### ISSUE THREAD

**Issue by modongmoqiu** [qipeng/golden-retriever#4]
excuse me, i am something doubt about the query generator you mentioned in the paper.
the second query generated from the previous query is just a oracle phrase or some words instead of a complete query sentence?

**Comment by qipeng** [comment]
The queries (regardless of which hop they are for) are always overlapping phrases or words in a contiguous span in the retrieval context (question + 0 or more retrieved documents concatenated) instead of complete sentences -- they also sometimes tend to work slightly better than complete sentences because we can remove some irrelevant noise in the sentences (see Hop 1 recall for the first paragraph vs single-hop query with the question in the paper). Hope this helps!

**Comment by modongmoqiu** [comment]
i see, thanks so much
